### ISSUE TITLE
Coupon for free shipping gets ignored by pick up locations shipping method

### ISSUE THREAD

**Issue by rhaselager** [SendCloud/sendcloud#134]
#### What steps will reproduce the problem?

1. We've configured a coupon for free delivery

2. Go to cart page and fill in a coupon that enables "free delivery"

3. Go to checkout -> select shipping method

#### What is the expected result?

* All shipping methods should be "free"

#### What happens instead?

* Sendcloud shipping method "Pickup location", coupon for free delivery gets ignored
* All others are free

#### Please provide any additional information below.

* This seems like a mistake in the Sendcloud module. I tried to read in the Git documentation (<https://github.com/SendCloud/sendcloud>) but couldn't find much about it.

**Comment by ivabocheva** [comment]
Hi rhaselger, 

We will be looking at the issue you are reporting and get back to you with our findings. 

Kind regards, 

The Sendcloud team

**Comment by twist247** [comment]
Hi @ivabocheva ,

We faced the same issue. After checking the code, we found that the issue is most likely related to 'Condition' = 'Fixed fee shipping price' setting. If you check method SendCloud\SendCloud\Model\Carrier\SendCloud::collectFlatRate(), on line 177 you will see that it takes shipping price directly from settings. There is no code that calculates free boxes. As a result, if a free shipping cart price rule is configured, it doesn't get applied to the shipping rate.

So here are the steps to reproduce:

1. In the shipping method config set 'Condition' = 'Fixed fee shipping price' and define a fixed rate.
2. Create a cart price rule with a coupon code. In the 'Actions' section of the rule, set 'Free Shipping' = 'For matching items only'
3. Go to cart page and apply the coupon code
4. Go to checkout and check shipping method rates. The rate for the SendCloud method should be 0. But you will see the price configured in admin panel instead.

**Comment by logeecom** [comment]
Hi @twist247,

Thank you for providing us with the reproduction steps.

We are investigating the reported issue and will let you know as soon as we have more information.

Best regards.

**Comment by logeecom** [comment]
Hi @twist247,

Thank you once again for your detailed issue description.

After investigation, our team concluded that the legacy service point shipping method does not contain logic for checking free shipping conditions based on cart rules and it requires investigation. We suggest using a new **checkout service point delivery method** that contains logic for checking free shipping conditions based on cart rules.

However, if you wish to use the legacy service point shipping method, please forward your request via the Support page in sendcloud: https://app.sendcloud.com/v2/support or reach out to support@sendcloud.com.

I hope I have informed you sufficiently and wish you a great day!
Best regards.

**Comment by janssensjelle** [comment]
Any update on this?
