### ISSUE TITLE
Block class doesn't exist DynamicCheckoutDeprecatedMessage

### ISSUE THREAD

**Issue by tonimorilla** [SendCloud/sendcloud#158]
Hi
Class SendCloud\SendCloud\Block\System\Config\Form\DynamicCheckoutDeprecatedMessage doesn't exist. Error in store config.
sendcloud/configuration.
Thanks

**Comment by tanjalog** [comment]
Hi @tonimorilla 

Thanks for reaching out to us.

Let us investigate the issue you reported, and we will get back to you shortly.

Best regards

**Comment by tanjalog** [comment]
Hello @tonimorilla 

The request you made requires more investigation. 

The Sendcloud support team is the best to investigate more in-depth.

The thing is, we do not know what version of the plugin you are using, and what is a version of Magento 2 you are using, and perhaps some credentials should be needed to share in order to resolve the mentioned issue.

All that being said please forward your request via the Support page in sendcloud: https://app.sendcloud.com/v2/support or reach out to [support@sendcloud.com](mailto:support@sendcloud.com).

If possible please describe clearly the issue and forward the version of the system and plugin you use. 

We hope we have informed you sufficiently and wish you a great day!

**Comment by tonimorilla** [comment]
Hi
Magento version is 2.4.6
Plugin version 2.0.18. Install via composer without specify version.
Error when I go to configure module. Class SendCloud\SendCloud\Block\System\Config\Form\DynamicCheckoutDeprecatedMessage doesn't exist. 
This class is defined in ui component form "vendor/sendcloud/sendcloud/view/adminhtml/ui_component/configuration_form.xml"
I can't send permissions because Site is in my local environment. If you have test environment you could check this error with this versions. Or check class declaration to compare with real path into the module

**Comment by tanjalog** [comment]
Hello @tonimorilla 

Thanks for the update.

Please note that in the latest version of SendCloud plugin v2.0.18 Dynamic checkout configuration is deprecated.

If you updated the plugin to the latest version(from the previous version that had Dynamic checkout) please remove the Dynamic checkout configuration and it will work properly.

Hope this helps.

Best regards

**Comment by tonimorilla** [comment]
Hello @tanjalog 
More info.
It isn't update. It 's a fresh install with composer. Then when you execute composer and module is downloaded the current release contain this file /vendor/sendcloud/sendcloud/view/adminhtml/ui_component/configuration_form.xml that contain error with class declaration. You can check source. Master branch contain the same error. it's possible that your  developers merge bad code or create release with this error?
Thank

**Comment by logeecom** [comment]
Hi @tonimorilla 

Thanks for contacting us one more time, we really appreciate it.

The Marketplace release was correct and the latest version is republished on git.

Best regards
